version: '3.8'

services:
  database:
    container_name: pricing_db
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=$MYSQL_DATABASE'
      - 'MYSQL_PASSWORD=$MYSQL_PASSWORD'
      - 'MYSQL_USER=$MYSQL_USER'
      - 'MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD'
    ports:
      - '${MYSQL_LOCAL_PORT}:${MYSQL_DOCKER_PORT}'
    volumes:
      - pricing-data:/var/lib/mysql
    restart: unless-stopped
  app:
    depends_on:
      - database
    image: pricing
    build:
      context: .
      dockerfile: Dockerfile
    env_file: ./.env
    environment:
      SPRING_APPLICATION_JSON: '{
              "spring.datasource.url"  : "jdbc:mysql://pricing_db:$MYSQL_DOCKER_PORT/$MYSQL_DATABASE?createDatabaseIfNotExist=true",
              "spring.datasource.username" : "$MYSQL_USER",
              "spring.datasource.password" : "$MYSQL_PASSWORD",
              "spring.datasource.driver-class-name" : "com.mysql.cj.jdbc.Driver",
              "spring.jpa.hibernate.ddl-auto" : "update"
            }'
    ports:
      - '${SPRING_LOCAL_PORT}:${SPRING_DOCKER_PORT}'
volumes:
  pricing-data: